database:
  host: ${USER_DB_HOST}
  user: ${USER_DB_USER}
  password: ${USER_DB_PASSWORD}
  db_name: ${USER_DB_NAME}
  port: ${USER_DB_PORT}
  ssl_mode: ${USER_DB_SSL_MODE}
  schema: "public"

server:
  address: "0.0.0.0"

fiber:
  app_name: "PushPost User-Service"
  port: 8081


jwt_secret: "pushpost"

